---
output: 
    stevetemplates::statement:
    latex_engine: pdflatex
geometry: margin=1in

title: "Research Plans"
author: Gustavo Diaz
affiliation: Center for Inter-American Policy and Research, Tulane University
email: "gustavodiaz@tulane.edu"

fontfamily: cochineal
fontsize: 11pt
---


```{r setup, include=F}
# a name for methods fields to change depending on specificity

methods = "quantitative methods"
```

<!-- Intro statement for apps that do not require cover letter. -->
<!-- I am writing to express my interest in your call for a Postdoctoral Fellowship at the Penn Development Research Initiative. I am a postdoctoral fellow at the Center for Inter-American Policy and Research at Tulane University. I specialize in comparative politics and quantitative methods. I received my PhD from the Department of Political Science at the University of Illinois at Urbana-Champaign under the supervision of Jake Bowers, Matt Winters, Gisela Sin, and Avital Livny. -->

My work contributes to two research programs. Substantively, I research political economy and political behavior in the Global South, with a focus on how information shapes accountability and representation. My main research agenda on this topic leverages a novel data collection effort in Brazil to study the unintended electoral consequences of exposing corruption that stem from politicians' strategic behavior. Methodologically, I use tools from design-based causal inference and machine learning to improve research design in experiments and observational studies, with emphasis on tools to for understanding hard-to-observe social and political phenomena. My current research on this topic focuses on two areas: modeling spillovers with partially unobserved networks and navigating the bias-variance trade-off in the design and analysis of field and survey experiments. Here I detail how these agendas will evolve in the next five years.

# The unintended electoral consequences of exposing corruption

My current research program focuses on the unintended consequences of investigating and publicizing corruption that stem from politicians' strategic behavior. Under this frame, my work shows how Brazilian mayors undertake preemptive behavior to ward-off the electoral backlash that may come from corruption investigations.

<!-- Work with Kelly -->
This program is evolving towards the gendered electoral consequences of corruption. In joint work with Kelly Senters Piazza (US Air Force Academy). In a  forthcoming book chapter prepared for the Interdisciplinary Corruption Research Network, we use my data on corruption infractions at the local level in Brazil to revisit previous findings on the gendered electoral consequences of corruption. Previous work in this topic uses public opinion data and survey experiments to show how revealing corruption increases support for female representation, yet also how female politicians face harsher sanctions for comparable levels of corruption. We argue that these methods of inquiry do not allow us to translate their conclusions to realistic settings, which we overcome by focusing on the aforementioned anti-corruption program in Brazil. We show that revealing corruption increases support for female representation in the form of an increased proportion of female candidates running for mayor, yet this support does not translate into an increased proportion of women winning elections, which we attribute to incumbent mayors' incentives to counter the rise of female challengers.

We are currently working to follow this with another book chapter to appear in a handbook on gender and corruption edited by Tiffany Barnes and Emily Beaulieu Bacchus (Kentucky). We discuss data sources to study the relationship between gender and corruption, with attention to the use of surveys and surveys experiments to understand whether voters evaluate politicians' corruption differently depending on their gender. This sets the stage for future projects. In the immediate future, we plan to conduct a meta-analysis of survey experiments on vote choice that manipulate politicians' gender and corruption record. This will help us understand the circumstances that explain variation in differential treatment. In the long term, we seek to advance a broader project that studies whether female politicians and candidate from other perceived minority groups are more likely to be held accountable for the transgressions of other group members.

# Improving tools to understand hard-to-observe phenomena

My current methodological research program focuses on improving research design and analysis in cases where the researcher has little control on the generation process. For example, my piece on a model selection approach to interference focuses on cases in which the researcher cannot directly manipulate the distribution of treatments in a network, but still wishes to understand interference or spillover effects in that network using causal inference tools. This program is now returning to focus on addressing bias-variance trade-offs when researchers can afford manipulation. I focus on the trade-offs in designing and analyzing survey and field experiments. In a chapter with Christopher Grady (USAID) and Jim Kuklinski (Illinois) in *The SAGE Handbook of Research Methods in Political Science and International Relations*, we discuss the trend of increasingly more complex research designs in survey experimentation. For example, short vignettes are replaced with factorial experiments including many attributes. This increase in complexity allows researchers to isolate causal effects from the role of potential confounders, but raises concerns over whether the tasks that respondents face in survey experiments tap into the intended construct outside of the survey framework.

In work under review, I apply the insights of our handbook chapter to the case of double list experiments. Social scientists use list experiments in surveys when respondents may not answer truthfully to sensitive questions directly. While list experiments reduce sensitivity biases from misreporting, they come at the cost of estimates with high variance, which prevents researchers from improving upon direct questioning. Double list experiments promise to remedy this by implementing two parallel list experiments and then aggregating their results, which roughly halves the variance of standard list experiment estimates. However, their implementation brings the question over whether the aggregation of the results of two different experiments yields a valid estimate. I propose a statistical test to assess the validity of estimates from double list experiments by leveraging variation in the order in which respondents receive the sensitive item, which provides researchers with a tool to apply this technique more widely.

An ongoing collaboration with Jake Bowers (Illinois) and Christopher Grady, with preliminary findings appearing in a blog post discussing methodological standards for Evidence in Governance and Politics (EGAP), illustrates a similar trade-off. We discuss the circumstances under which researchers should prefer biased yet more precise estimates in the analysis of experimental data. This goes against the tendency in the statistics and the social sciences to prefer unbiased estimates. An example of this trade-off comes from the analysis of block-randomized experiments. Block-randomization entails grouping observations in blocks or strata, conducting parallel experiments in each, and then calculating a single treatment effect with a weighted average. Previous work in statistics suggests that block-size weights lead to an unbiased estimator of the average treatment effect in this setting. However, because experiments are expensive to implement, we illustrate situations in which researchers may prefer to sacrifice unbiasedness in favor of more precise estimates, which would lead to the use of precision weights instead, the equivalent of using fixed effects in OLS regression. We extend this idea to other estimation techniques, including covariance adjustment and M-estimation. Through this exercise, we invite researchers to navigate this trade-off before implementing experimental interventions, and to incorporate adaptive rules in the choice of the appropriate estimator in pre-analysis plans.

I foresee producing similar insights in the short term. For example, in work in progress with Erin Rossiter (Notre Dame), we discuss the precision-attrition trade-off in implementing research designs that require collecting data before conducting an experiment, including block-randomization and pre-post measurement of outcome variables. In the long term, I expect these efforts to inform and impact the research design of broader collaborative projects on accountability and representation.









