---
output: 
    stevetemplates::statement:
    latex_engine: pdflatex
geometry: margin=1in

title: "Summary Addressing Selection Criteria"
author: Gustavo Diaz
affiliation: Center for Inter-American Policy and Research, Tulane University
email: "gustavodiaz@tulane.edu"

fontfamily: cochineal
fontsize: 11pt
---

# 1. PhD in a political science or a relevant discipline in the social sciences

I received my PhD in political science from the University of Illinois at Urbana-Champaign in August 2021.

# 2.	Demonstrated track record to undertake research and evidence of a well-developed research agenda 

Substantively, I research political economy and political behavior in the Global South, with a focus on how information shapes accountability and representation. Methodologically, I use tools from design-based causal inference and machine learning to improve research design in experiments and observational studies. 

<!-- Remember to update the status of stuff sent for review -->
<!-- Nearby corruption -->
My primary substantive research agenda studies the unintended electoral consequences of corruption that stem from politicians' strategic behavior. In work funded by the Lemann Center for Brazilian Studies at the University of Illinois, I show how revealed corruption drives politicians in nearby municipalities to undertake preemptive behavior to ward off a negative reaction from their constituents.  Whereas previous literature has shown evidence that partisans might react strategically to anticipated sanctions when their political party is linked to corruption, my work shows that this behavior is even more widespread and that politicians fear being caught in an electoral anti-corruption wave even when there is no evidence of their own wrong-doing. I advance this argument using data from a long-running anti-corruption program in Brazil that randomly selects municipalities for auditing and publicizes its findings, combining text analysis and machine learning to construct the most comprehensive dataset of corruption infractions to date. I show how mayors exposed to nearby corruption switch parties more often only when they have reelection-related incentives and that they do so because they attempt to secure more resources to counter an expected increase in public scrutiny from their constituencies.

<!-- Gender corruption -->
With Kelly Senters Piazza (US Air Force Academy), I maintain a research program on the gendered electoral consequences of corruption. In a book chapter in preparation for the Interdisciplinary Corruption Research Network, we use my original data on corruption infractions in Brazil to show how corruption revelation increases the proportion of female candidates running for mayor but not their chances of winning elections, which we attribute to incumbents' incentives to counter the rise of female politicians. This invites us to pay more attention to the role of established elites in understanding the factors that shape female political representation. In a viewpoint article in *World Development*, we use the lessons from our work on corruption to discuss how the COVID-19 pandemic has the potential to promote female political representation through increased discontent with the performance of male-led executives and by priming a health policy issue commonly associated with women. 

<!-- Modeling spillovers -->
My methodological research agenda uses the lessons of my substantive work to improve our tools for understanding of hard-to-observe social and political phenomena. I extend my work on exposure to nearby corruption in Brazil to the question of how to analyze spillover effects in settings where the researcher observes units' placement in a network, but not how they connect to each other. Previous methods assume that the researcher observes all relevant networks directly, but this level of control is rare in many experimental and observational studies. I propose a model selection protocol that overcomes this difficulty. They key is to express units' placement in the network in terms of a distance metric, which lets the researcher identify and choose among alternative model specifications that follow from a single theoretical framework. 

<!-- Survey experiments and block rand -->
I also maintain an agenda on improving research design in survey and field experiments. In a chapter with Christopher Grady (USAID) and Jim Kuklinski (Illinois) in *The SAGE Handbook of Research Methods in Political Science and International Relations*, we discuss the merits and challenges of increased complexity in the design of survey experiments. I bring the lessons of our chapter to a solo-authored working paper that introduces new tools to assess the validity of findings in double list experiments. This is a variant of the list experiment survey technique for asking sensitive questions.  While the double list experiment promises more precise prevalence estimates, it comes with questionnaire design complications that remain under-explored. In work in progress with Jake Bowers (Illinois) and Christopher Grady, we caution against rules of thumb in the estimation of treatment effects in block-randomized experiments, since the bias and precision of alternative estimation strategies depends on the size of blocks, the number of treated units within each block, and the distribution of treatment effects across them.


# 3.	Evidence of high quality teaching, including preparation and delivery of lectures tutorials and assessment, as evidenced by good oral and written English communication skills and teaching evaluations

I have experience teaching substantive and methodological courses to diverse audiences and under different formats. At Tulane, I teach Introduction to Comparative Politics, focusing on theoretical and methodological considerations. In my time at Illinois, I taught an online course on the politics of developing countries as an independent instructor and served as a teaching assistant for its in-person version. I also served as a teaching assistant for quantitative research methods courses at the undergraduate and PhD levels using a flipped classroom approach. I served as a math camp instructor for incoming graduate students for three consecutive years and started a collaborative project in which graduate students introduce their peers to new methodological tools.

I am prepared to teach courses on the politics of the Global South, data analysis, and research design. I am also eager to teach my own graduate seminar on the design and analysis of experiments. You can find copies of current and sample syllabi on my website. As a first generation scholar, my teaching philosophy approaches the classroom as an opportunity to build skills for students with different backgrounds, career goals, and learning styles.

# 4. Ability to supervise student research projects at the Honours and postgraduate levels

 In the 2020-2021 academic year, I was the graduate methods teaching assistant in our department. My duties involved advising PhD students taking courses in the quantitative methods sequence, as well as mentoring undergraduates enrolled in the senior honors thesis program. I also was a teaching assistant for the causal inference track at the IPSA-USP Summer School in Concepts, Methods, and Techniques at the University of São Paulo in 2020, discussing with fellow academics how to make productive causal critiques to the implementation of causal inference research designs in observational studies (e.g. instrumental variables, regression discontinuity, difference-in-differences).
 
I have also enjoyed the experience of mentoring an undergraduate research assistant, using the opportunity to help both of us learn text analysis. 
 
I organized a reading group on computational social science at Illinois that met regularly in the Summer and Fall of 2017. I started a a collaborative project in which graduate students share cheatsheets introducing their fellows to new methodological tools. 

# 5.	Capacity to undertake effective administration and leadership at the School and College level

I organized a reading group on computational social science at Illinois that met regularly in the Summer and Fall of 2017. In 2018, I started a a collaborative project in which graduate students share cheatsheets introducing their fellows to new methodological tools. In 2019, I serves the graduate student member in the search committee to hire an Assistant Professor in Comparative Politics and Data Science. These experiences prepared me to perform key administrative duties.

# 6. Demonstrated ability to communicate and interact effectively with a variety of staff and students and the proven ability to promote, develop and maintain strong collaborative relationships both nationally and internationally

In my time at Illinois, I engaged actively as a member of the intellectual community in every dimension, especially
in seminars, workshops, and the initiatives mentioned in the previous item. I am also a regular participant in the Latin American Political Methodology meeting since its creation. Through that platform, I have a developed a network with scholars throughout the region. 

# 7.	Demonstrated ability to foster inclusive, respectful and productive working relationships with staff, students and colleagues at all levels

I had experience engaging with staff, students, and faculty throughout my PhD studies. My primary goal is to create, facilitate, and participate in spaces where all voices are heard.

# 8. A demonstrated high-level of understanding of equal opportunity principles and a commitment to the application of EO policies in a University context

I recognize that the university setting may not be a welcoming environment for individuals from underserved communities that have not been exposed to the hidden curriculum. Throughout all aspects of my work, I seek to create opportunities so that the voices of individuals who do not thrive in the conventional university teaching are heard. In my teaching, this is reflecting on emphasizing the value of out-of-classroom activities for participation and learning. In my research, I seek to foster continuous collaborative environments that allow participants to contribute from their own preferences and expertise.
