---
title: "Teaching"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Sample Syllabi

These are sample syllabi of courses that I plan to teach in the future. Feel free to use them for your own purposes.

### Graduate

[Advances in the Design and Analysis of Experiments](files/teaching/exp_syllabus.pdf)

### Undergraduate

[Comparative Politics in Developing Countries](files/teaching/cpdev_syllabus.pdf)

[Political Data Analysis](files/teaching/data_syllabus.pdf)

## Instructor

### Tulane University

Comparative Politics

### University of Illinois at Urbana-Champaign

Comparative Politics in Developing Nations (Online) [`Syllabus`](files/teaching/cpdev_online_syllabus.pdf)

Math Camp for Political Scientists [`GitHub`](https://github.com/mathcamp-psgsa)

## Teaching Assistant

### University of Illinois at Urbana-Champaign

#### Graduate

Quantitative Methods I (Instructor: [Brian Gaines](https://pol.illinois.edu/directory/profile/bjgaines))

Quantitative Methods II  (Instructor: [Jake Bowers](https://www.jakebowers.org/))

Quantitative Methods III (Instructor: [Wendy K. Tam Cho](https://cho.pol.illinois.edu/wendy/))

Research Design and Techniques (Instructors: [Jake Bowers](https://www.jakebowers.org/) and [James H. Kuklinski](https://pol.illinois.edu/directory/profile/kuklinsk))

#### Undergraduate

Quantitative Methods (Instructor: [Jake Bowers](https://www.jakebowers.org/))

Comparative Politics in Developing Nations (Instructor: [Avital Livny](https://pol.illinois.edu/directory/profile/alivny))

### Pontificia Universidad Católica de Chile

Introduction to Comparative Politics (Instructor: [Valeria Palanza](https://valeriapalanza.com/))

Qualitative Methods (Instructor: [Julieta Suárez-Cao](https://www.cienciapolitica.uc.cl/profesores/planta-academica/julieta-suarez-c))

Subnational Politics in Latin America (Instructor: [Julieta Suárez-Cao](https://www.cienciapolitica.uc.cl/profesores/planta-academica/julieta-suarez-c))






