---
title: "Quiz Figures"
author: "Gustavo Diaz"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(kableExtra)
library(fontawesome)

# ggplot global options
theme_set(theme_classic(base_size = 20))
```

# Quiz 4

## Single-peaked preferences

```{r}
peak = data.frame(
  policy = 1:3,
  utility = 1:3
)

peak_plot = ggplot(peak) +
  aes(x = policy, y = utility) +
  geom_line(size = 3) +
  scale_x_continuous(breaks = 1:3, labels = c("Decrease", "Keep", "Increase")) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(x = "Education funding", y = "Utility")

ggsave(plot = peak_plot, filename = "q4_peak.png", height = 6, width = 12)
```

## Multiple dimensions

```{r}
dims = ggplot() +
  labs(x = "% subsidies to capital", y = "% subsidies to labor") +
  geom_abline(intercept = 100, slope = -1, linetype = "dashed", size = 1) +
  geom_point(aes(x = 100/3, y = 100/3), size = 3) +
  annotate("text", x = 100/3 + 5, y = 100/3 + 5, label = "SQ", size = 6) +
  geom_linerange(aes(y = 100/3, xmin = -Inf, xmax = 200/3), linetype = "dotted") +
  geom_linerange(aes(x = 100/3, ymin = -Inf, ymax = 200/3), linetype = "dotted") +
  geom_abline(intercept = 200/3, slope = -1, linetype = "dotted") +
  geom_point(aes(x = 50, y = 10), size = 3) +
  annotate("text", x = 47, y = 7, label = "P", size = 6) +
  scale_x_continuous(expand = c(0,1), breaks = c(0, 100/3, 100), labels = c("0", "33.3", "100")) +
  scale_y_continuous(expand = c(0,1), breaks = c(0, 100/3, 100), labels = c("0", "33.3", "100")) +
  coord_cartesian(xlim = c(0, 100), ylim = c(0, 100))

ggsave(plot = dims, filename = "q4_dims.png", height = 6, width = 12)
```

## Least connected MWC

```{r, fig.height=2, fig.width=12}
# Chile senate seats
seats = data.frame(
  coalition = c("Apruebo\nDignidad", "Nuevo\nPacto Social", "Independents", " Chile\nPodemos +", "Frente Social\nCristiano"),
  seats = c("5", "17", "3", "24", "1"),
  token = c(rep(0, 5))
)

seats$seats = fct_relevel(seats$seats, "5", "17", "3", "24", "1")


seats_plot = ggplot(seats) +
  aes(x = seats, y = token, label = coalition) +
  labs(x = "Seats") +
  geom_text(size = 5) +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_blank())

ggsave(plot = seats_plot, filename = "q4_seats.png", height = 2, width = 12)
```

