---
title: "News Reports"
subtitle: "Comparative Politics"  
date: "September 27-October 1, 2021"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%/%total%" 
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)

library(knitr)
opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = FALSE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  title_slide_background_image = "figs/logo.png",
  title_slide_background_size = "8%",
  title_slide_background_position = "50% 95%",
  primary_color = "#336666",
  secondary_color = "#71C5E8",
  inverse_header_color = "#FFFFFF",
  background_color = "#EAE9EA",
  link_color = "#71C5E8",
  # easy to fetch colors
  colors = c( 
    white = "#FFFFFF",
    green = "#336666",
    lblue = "#71C5E8"
    )
)



```

```{r other-options}
library(knitr)
library(tidyverse)
library(kableExtra)
library(fontawesome)
```

## 5 News Reports

```{r}
dates = data.frame(
  Assignment = c("News Report 1", "News Report 2", "News Report 3", 
                 "News Report 4", "News Report 5"),
  Date = c("October 1", "October 15","October 29", "November 12", "December 10")
)

dates %>% 
  kbl()
```
