---
output: stevetemplates::cover_letter
geometry: margin=1in
header-includes:
  - \pagenumbering{gobble}

author: Gustavo Diaz
address: |
    | Center for Inter-American Policy and Research
    | Tulane University
    | 7025 Freret Street
    | New Orleans, LA 70118 USA
email: "gustavodiaz@tulane.edu"
url: gustavodiaz.org
phone: +1 217 904 0581
fontsize: 11pt
mainfont: cochineal
monofont: Fira Code

fontawesome: TRUE
date: '`r format(Sys.Date(), "%B %d, %Y")`'
greetings: "Dear Members of the Search Committee,"
---

```{r setup, include=F}

jobtitle = "a Lecturer in Politics or International Relations"
place = "The University of Edinburgh"
```

I write to express my interest in your call for `r jobtitle`. I am a postdoctoral fellow at the Center for Inter-American Policy and Research at Tulane University. I specialize in quantitative methods and comparative politics. I received my PhD from the Department of Political Science at the University of Illinois at Urbana-Champaign under the supervision of Jake Bowers, Matt Winters, Gisela Sin, and Avital Livny.

I research the application of tools from design-based causal inference and data science to improve research design in experiments and observational studies. I base my insights on my substantive work on the challenges to democratic accountability and representation in the Global South. My work appears in *World Development* and *The SAGE Handbook for Research Methods in Political Science and International Relations*, and has been funded by the Lemann Center for Brazilian Studies at the University of Illinois.

<!-- RESEARCH -->
<!-- Remember to update the status of stuff sent for review -->
<!-- Try to write about methods work in a way that seems coherent -->
<!-- Modeling spillovers -->
My primary agenda focuses on improving our tools for understanding hard-to-observe social and political phenomena along two research programs. The first research program focuses on analyzing spillover effects in settings where the researcher observes units' placement in a network, but not how they connect to each other. Previous work approaching this problem from a causal inference perspective assumes the researcher observes all relevant networks directly, but this level of control is rare in experiments and observational studies, which means one cannot justify the required identification assumptions. I propose a model selection protocol that overcomes this difficulty. The key is to use a distance metric to identify alternative model specifications that follow from a theory, and then choose among them using a model selection technique of choice. I illustrate the usefulness of this approach in the context of supervised learning model selection by revisiting the findings of an experiment on the spillover effects of election observers on voter registration irregularities in Ghana.

<!-- Survey experiments and block rand -->
The second research program focuses on navigating the bias-variance trade-off in survey and field experiments. At the design stage, researchers must choose whether to implement simple, intuitive experimental designs with imprecise estimates, or complex designs that are more precise yet difficult to connect with social and political phenomena of interest. In a chapter with Christopher Grady (USAID) and Jim Kuklinski (Illinois) in *The SAGE Handbook of Research Methods in Political Science and International Relations*, we discuss the merits and challenges of increased complexity in the design of survey experiments. I bring the lessons of our chapter to a solo-authored piece under review that introduces new tools to assess the validity of findings in double list experiments. This variant of the list experiment promises more precise prevalence estimates but comes with under-explored questionnaire design complications. In a working paper with Jake Bowers (Illinois) and Christopher Grady, we discuss the circumstances under which researchers should prefer biased yet precise estimates to analyze experimental data, including applications to block-randomization, covariance adjustment, and M-estimation. 

<!-- In work in progress with Erin Rossiter (Notre Dame), we establish standards to navigate the trade-off between estimate precision and respondent attrition in experimental design. -->

<!-- SUBSTANTIVE WORK -->
<!-- Nearby corruption -->
I apply the insights of my methodological work to a substantive agenda that relies on an original data collection effort in Brazil, combining text analysis and machine learning to construct the most comprehensive dataset of corruption infractions at the local level. I study the unintended electoral consequences of corruption that stem from politicians' strategic behavior. Applying my model selection approach, I show how corruption revelation drives politicians in nearby municipalities to undertake preemptive behavior to ward off a negative reaction from their constituents.  Whereas previous literature has shown evidence that partisans might react strategically to anticipate sanctions when their political party is linked to corruption, my work shows that this behavior is even more widespread, and that politicians fear being caught in an electoral anti-corruption wave even when there is no evidence of their own wrong-doing.

<!-- Gender corruption -->
I  also maintain a research program on the gendered electoral consequences of corruption with Kelly Senters Piazza (US Air Force Academy). In a forthcoming book chapter prepared for the Interdisciplinary Corruption Research Network, we use my corruption infractions dataset to show how corruption revelation increases the proportion of female candidates running for mayor, but not their chances of winning elections. We attribute this to incumbents' incentives to counter the rise of female politicians. In a viewpoint article in *World Development*, we use the lessons from our work on corruption to discuss how the COVID-19 pandemic has the potential to promote female political representation through increased discontent with the performance of male-led executives and by priming a health policy issue commonly associated with women. 

<!-- We extend our collaboration to work in progress with Justin Esarey (Wake Forest). We conduct a meta-analysis of survey experiments on gender and corruption to understand the circumstances under which voters evaluate female candidates differently, since previous research suggests that similar causal mechanisms may lead to differential punishment on reward. -->

<!-- Placeholder for work with Matt Winters -->

<!-- TEACHING -->
<!-- UIUC -->
I have experience teaching courses in quantitative methods and comparative politics. At Tulane, I teach Introduction to Comparative Politics, focusing on theoretical considerations and policy implications, and a course on evidence-informed policy making to address social challenges in developing democracies. In my time at Illinois, I served as a teaching assistant for statistics courses at the undergraduate and PhD levels using a flipped classroom approach. I served as a math camp instructor for incoming graduate students for three consecutive years and started a collaborative project in which graduate students introduced their peers to new methodological tools. I also taught an online course on the politics of developing countries as an independent instructor and served as a teaching assistant for its in-person version. These experiences have prepared me to teach to a diverse student body, to adapt to both online and in-person platforms, and to teach at the intersection of applied and methodological work.

<!-- Teaching plans -->
<!-- Remember to switch from teaching portfolio/website accordingly -->
<!-- Also tweak depending on job -->
I am prepared to teach courses on causal inference, computational social science, evidence-informed policy making, and the politics of the Global South. You can find copies of current and sample syllabi in my website. As a first-generation scholar, my teaching philosophy emphasizes building skills for students with different backgrounds, learning styles, and career goals.

<!-- CLOSING -->
I believe my expertise would make me an excellent fit at `r place`. Please find enclosed the materials supporting my application. If you have any questions, you can contact me via e-mail or phone.


Sincerely,

<!-- Remember double spaces to lineskip -->
Gustavo Diaz  
<!-- Postdoctoral Fellow   -->
Center for Inter-American Policy and Research  
Tulane University
